# Generated by Django 4.0.6 on 2023-10-31 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.ImageField(upload_to='')),
                ('message', models.TextField(max_length=1000)),
                ('time_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
