# Generated by Django 4.0.6 on 2023-10-16 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('email', models.EmailField(max_length=100, verbose_name='Gmail')),
                ('specialization', models.CharField(max_length=100, verbose_name='Специализация')),
                ('mobile', models.CharField(max_length=100, verbose_name='Телефон')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('photo', models.ImageField(upload_to='user_photo/')),
            ],
            options={
                'verbose_name_plural': 'Блог',
            },
        ),
    ]
