# Generated by Django 4.0.6 on 2023-12-16 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Blogs',
        ),
        migrations.AlterModelOptions(
            name='blogs',
            options={},
        ),
    ]
